# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

fib_sum = 0
fibonacci = [1,2]

while fibonacci[-1] < 4000000:
    new_value = fibonacci[-1] + fibonacci[-2]
    fibonacci.append(new_value)

for i in range(len(fibonacci) - 1):
    if fibonacci[i] % 2 == 0:
        fib_sum = fib_sum + fibonacci[i]

print(fib_sum)



    


