# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 
# 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
# The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
"""
1: 1
3: 1, 3
6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28
"""
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

tri_num = [1, 3, 6]
divisors = []

def is_500_divs(n):
    for i in range(1, int(n**(1/2)) + 1):
        if n % i == 0:
            divisors.append(i)
            if i != n // i:
                divisors.append(n // i)

a = 4
b = 6
while len(divisors) < 501:
    divisors.clear()
    b = b + a
    tri_num.append(b)
    a += 1
    is_500_divs(max(tri_num))

print("The value of the first triangle number to have over five hundred divisors: ", max(tri_num))
divisors.sort()
print("Total divisors: ", divisors)

